import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "node:module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const workerSourcePlugin = {
	name: "tsdb-worker-source",
	setup(build) {
		build.onResolve({ filter: /^tsdb-worker-source$/ }, (args) => ({
			path: args.path,
			namespace: "tsdb-worker-source",
		}));
		build.onLoad({ filter: /.*/, namespace: "tsdb-worker-source" }, async () => {
			const result = await esbuild.build({
				entryPoints: ["src/storage/tsdb-worker.ts"],
				bundle: true,
				write: false,
				format: "iife",
				target: "es2020",
				platform: "browser",
				define: {
					"process.env.NODE_ENV": prod ? '"production"' : '"development"',
					"import.meta.url": '"file:///tsdb/worker.js"',
				},
				logLevel: "silent",
				minify: prod,
				treeShaking: true,
				metafile: true,
			});
			const source = result.outputFiles[0].text;
			return {
				contents: `export default ${JSON.stringify(source)};`,
				loader: "js",
				watchFiles: Object.keys(result.metafile.inputs),
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	loader: {
		// Embed SQLite WASM in main.js but leave it encoded until the deferred
		// runtime startup. The binary loader would decode it during module load.
		".wasm": "base64",
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
		// wa-sqlite's emscripten glue eagerly computes
		// `new URL("wa-sqlite-async.wasm", import.meta.url)`; under cjs output
		// import.meta.url would be undefined and that constructor throws. The
		// URL is never fetched (we inject wasmBinary), it just must be valid.
		"import.meta.url": '"file:///tsdb/main.js"',
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"http",
		"url",
		...builtins,
		...builtins.map((name) => `node:${name}`)],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [workerSourcePlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
