import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	loader: {
		// Embed the sql.js SQLite WASM binary directly into main.js so the
		// plugin ships as a single file per Obsidian plugin requirements.
		".wasm": "binary",
	},
	define: {
		"process.env.NODE_ENV": prod ? '"production"' : '"development"',
		// wa-sqlite's emscripten glue eagerly computes
		// `new URL("wa-sqlite-async.wasm", import.meta.url)`; under cjs output
		// import.meta.url would be undefined and that constructor throws. The
		// URL is never fetched (we inject wasmBinary), it just must be valid.
		"import.meta.url": '"file:///tsdb/main.js"',
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		"http",
		"url",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
